export default {
    address: {
        delete: 'delete',
        getAreas: 'getAreas',
        getCities: 'getCities',
        getSettlements: 'getSettlements',
        getStreet: 'getStreet',
        getWarehouses: 'getWarehouses',
        getWarehouseTypes: 'getWarehouseTypes',
        save: 'save',
        searchSettlements: 'searchSettlements',
        searchSettlementStreets: 'searchSettlementStreets',
        update: 'update',
    },
    common: {
        getBackwardDeliveryCargoTypes: 'getBackwardDeliveryCargoTypes',
        getCargoDescriptionList: 'getCargoDescriptionList',
        getCargoTypes: 'getCargoTypes',
        getMessageCodeText: 'getMessageCodeText',
        getOwnershipFormsList: 'getOwnershipFormsList',
        getPackList: 'getPackList',
        getPalletsList: 'getPalletsList',
        getPaymentForms: 'getPaymentForms',
        getServiceTypes: 'getServiceTypes',
        getTimeIntervals: 'getTimeIntervals',
        getTiresWheelsList: 'getTiresWheelsList',
        getTypesOfCounterparties: 'getTypesOfCounterparties',
        getTypesOfPayers: 'getTypesOfPayers',
        getTypesOfPayersForRedelivery: 'getTypesOfPayersForRedelivery',
    },
    counterparty: {
        delete: 'delete',
        getCounterpartyAddresses: 'getCounterpartyAddresses',
        getCounterpartyOptions: 'getCounterpartyOptions',
        getCounterpartyContactPersons: 'getCounterpartyContactPersons',
        getCounterparties: 'getCounterparties',
        save: 'save',
        update: 'update',
    },
    contactPerson: {
        delete: 'delete',
        save: 'save',
        update: 'update'
    },
    internetDocument: {
        delete: 'delete',
        generateReport: 'generateReport',
        getDocumentDeliveryDate: 'getDocumentDeliveryDate',
        getDocumentList: 'getDocumentList',
        getDocumentPrice: 'getDocumentPrice',
        getStatusDocuments: 'getStatusDocuments',
        save: 'save',
        update: 'update',
    },
    scanSheet: {
        deleteScanSheet: 'deleteScanSheet',
        insertDocuments: 'insertDocuments',
        getScanSheet: 'getScanSheet',
        getScanSheetList: 'getScanSheetList',
        removeDocuments: 'removeDocuments',
    },
    additionalService: {
        delete: 'delete',
        getChangeEWOrdersList: 'getChangeEWOrdersList',
        getRedirectionOrdersList: 'getRedirectionOrdersList',
        getReturnOrdersList: 'getReturnOrdersList',
        getReturnReasons: 'getReturnReasons',
        getReturnReasonsSubtypes: 'getReturnReasonsSubtypes',
        CheckPossibilityChangeEW: 'CheckPossibilityChangeEW',
        CheckPossibilityCreateReturn: 'CheckPossibilityCreateReturn',
        save: 'save',
    },
    additionalServiceGeneral: {
        delete: 'delete',
        checkPossibilityForRedirecting: 'checkPossibilityForRedirecting',
        save: 'save',
    },
};
