export const methods = {
    address: [
		'delete',
		'getAreas',
		'getCities',
		'getSettlements',
		'getStreet',
		'getWarehouses',
		'getWarehouseTypes',
		'save',
		'searchSettlements',
		'searchSettlementStreets',
		'update',
	],
	common: [
		'getBackwardDeliveryCargoTypes',
		'getCargoDescriptionList',
		'getCargoTypes',
		'getMessageCodeText',
		'getOwnershipFormsList',
		'getPackList',
		'getPalletsList',
		'getPaymentForms',
		'getServiceTypes',
		'getTimeIntervals',
		'getTiresWheelsList',
		'getTypesOfCounterparties',
		'getTypesOfPayers',
		'getTypesOfPayersForRedelivery',
	],
	counterparty: [
		'delete',
		'getCounterpartyAddresses',
		'getCounterpartyOptions',
		'getCounterpartyContactPersons',
		'getCounterparties',
		'save',
		'update'
	],
	contactPerson: [
		'delete',
		'save',
		'update',
	],
	internetDocument: [
		'delete',
		'generateReport',
		'getDocumentDeliveryDate',
		'getDocumentList',
		'getDocumentPrice',
		'getStatusDocuments',
		'save',
		'update',
	],
	scanSheet: [
		'deleteScanSheet',
		'insertDocuments',
		'getScanSheet',
		'getScanSheetList',
		'removeDocuments',
	],
	additionalService: [
		'delete',
		'getChangeEWOrdersList',
		'getRedirectionOrdersList',
		'getReturnOrdersList',
		'getReturnReasons',
		'getReturnReasonsSubtypes',
		'CheckPossibilityChangeEW',
		'CheckPossibilityCreateReturn',
		'save',
	],
	additionalServiceGeneral: [
		'delete',
		'checkPossibilityForRedirecting',
		'save',
	]
}